@extends('layouts.app')
@section('title', 'Cristalcopo - Subgrupo de Avaliação')
@section('content')
@php($editing = $subgrupo->exists)
<div class="content-wrapper"><div class="container-full"><div class="content-header"><h4 class="page-title">{{ $editing ? 'Editar subgrupo' : 'Novo subgrupo' }}</h4></div><section class="content">
<form method="POST" action="{{ $editing ? route('avaliacoes.desempenho.subgrupos.update', $subgrupo->id) : route('avaliacoes.desempenho.subgrupos.store') }}">@csrf @if($editing) @method('PUT') @endif
<div class="box"><div class="box-body"><input type="hidden" name="grupo_id" value="{{ old('grupo_id', $grupo->id) }}"><div class="row"><div class="col-md-6"><div class="form-group"><label class="form-label">Nome</label><input type="text" name="nome" class="form-control" value="{{ old('nome', $subgrupo->nome) }}" required></div></div><div class="col-md-3"><div class="form-group"><label class="form-label">Ordem</label><input type="number" name="ordem" class="form-control" value="{{ old('ordem', $subgrupo->ordem) }}" required></div></div><div class="col-md-3"><div class="form-group"><label class="form-label">Ativo</label><select name="ativo" class="form-control"><option value="1" @selected((int) old('ativo', $subgrupo->ativo)===1)>Sim</option><option value="0" @selected((int) old('ativo', $subgrupo->ativo)===0)>Não</option></select></div></div></div><div class="row"><div class="col-md-12"><div class="form-group"><label class="form-label">Descrição</label><textarea name="descricao" class="form-control" rows="3">{{ old('descricao', $subgrupo->descricao) }}</textarea></div></div></div></div></div>
@include('avaliacoes.desempenho.partials.regras-aplicacao')
<button class="btn btn-success">Salvar</button> <a class="btn btn-secondary" href="{{ route('avaliacoes.desempenho.ciclos.edit', $grupo->pilar->ciclo->id) }}">Voltar</a>
</form></section></div></div>
@endsection
@section('scripts')<script>window.adicionarLinhaRegra=function(button){const c=button.closest('.box').querySelector('.regras-container');const i=c.querySelectorAll('.regra-item').length;c.insertAdjacentHTML('beforeend',`<div class="row regra-item align-items-end mb-2"><div class="col-md-5"><label class="form-label">Tipo</label><select name="regras[${i}][regra_tipo]" class="form-control"><option value="cargo">Cargo</option><option value="filial">Filial</option><option value="setor">Setor</option></select></div><div class="col-md-5"><label class="form-label">Referência</label><input type="number" min="1" class="form-control" name="regras[${i}][referencia_id]"></div><div class="col-md-2"><button type="button" class="btn btn-danger btn-sm" onclick="this.closest('.regra-item').remove()">Remover</button></div></div>`);};</script>@endsection
